# Generated by Django 4.2.3 on 2023-09-02 18:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('locality', models.CharField(max_length=400)),
                ('city', models.CharField(max_length=50)),
                ('zipcode', models.IntegerField()),
                ('state', models.CharField(choices=[('Jharkhand', 'Jharkhand'), ('Kerala', 'Kerala'), ('Manipur', 'Manipur'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Gujarat', 'Gujarat'), ('Odisha', 'Odisha'), ('Rajasthan', 'Rajasthan'), ('Mizoram', 'Mizoram'), ('Haryana', 'Haryana'), ('Sikkim', 'Sikkim'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Tripura', 'Tripura'), ('Puducherry', 'Puducherry'), ('Delhi', 'Delhi'), ('Chhattisgarh', 'Chhattisgarh'), ('Lakshadweep', 'Lakshadweep'), ('Andaman and Nicobar Islands', 'Andaman and Nicobar Islands'), ('Jammu and Kashmir', 'Jammu and Kashmir'), ('Assam', 'Assam'), ('West Bengal', 'West Bengal'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Karnataka', 'Karnataka'), ('Goa', 'Goa'), ('Bihar', 'Bihar'), ('Punjab', 'Punjab'), ('Telangana', 'Telangana'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Tamil Nadu', 'Tamil Nadu'), ('Nagaland', 'Nagaland'), ('Chandigarh', 'Chandigarh'), ('Meghalaya', 'Meghalaya'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Dadra and Nagar Haveli', 'Dadra and Nagar Haveli'), ('Daman and Diu', 'Daman and Diu'), ('Maharashtra', 'Maharashtra'), ('Uttarakhand', 'Uttarakhand')], max_length=50)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'costomer',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('selling_price', models.FloatField()),
                ('discount_price', models.FloatField()),
                ('description', models.TextField(max_length=4000)),
                ('brand', models.CharField(max_length=400)),
                ('category', models.CharField(choices=[('Books', 'Books'), ('Mobile', 'Mobile'), ('Pant', 'Pant'), ('Jewellery', 'Jewellery'), ('Ethnic', 'Ethnic'), ('Shirt', 'Shirt'), ('Watch', 'Watch'), ('Jeans', 'Jeans'), ('Laptop', 'Laptop')], max_length=50)),
                ('stock', models.PositiveIntegerField()),
                ('product_image', models.ImageField(upload_to='productimg')),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('On Way', 'On Way'), ('Deliverd', 'Deliverd'), ('pending', 'pending'), ('Out For Delivery', 'Out For Delivery'), ('Accepted', 'Accepted')], default='pending', max_length=50)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.product')),
            ],
            options={
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.product')),
            ],
            options={
                'db_table': 'cart',
            },
        ),
    ]
